# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5283b72d26a53cf718947789675c82fce786ede867e746863e0e18ba90e772df4fdda57979f43714817574ce21dbf6d31cad2e09cb614ed049e017c32ae634a8

test:
  secret_key_base: 0e1c89d9e4ef5fc343b1ee3ade377a1ea8a3badf00c9d9cb32520e9de68138838940ea239fb417f91171b499619488c19fdc6851af7a62b012ca886ce3ff3996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
